import { AlertCircle, Monitor, Smartphone, Sparkles } from "lucide-react";
import { Button } from "./components/ui/button";
import { ButtonGroup } from "./components/ui/button-group";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldSet,
} from "./components/ui/field";
import { Textarea } from "./components/ui/textarea";
import z from "zod";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { cn } from "./lib/utils";
import { Alert } from "./components/ui/alert";

const videoFormSchema = z.object({
  prompt: z
    .string()
    .min(10, "Prompt must be at least 10 characters")
    .max(500, "Prompt must be under 500 characters"),
  quality: z.enum(["4k", "1080", "720", "480"], {
    message: "Please select a quality",
  }),
  duration: z.enum(["0.5-2 mins", "2-4 mins"], {
    message: "Please select a duration",
  }),
  orientation: z.enum(["landscape", "portrait"], {
    message: "Please select an orientation",
  }),
});

type VideoFormValues = z.infer<typeof videoFormSchema>;

const defaultValues: VideoFormValues = {
  prompt: "",
  quality: "4k",
  duration: "0.5-2 mins",
  orientation: "landscape",
};

function App() {
  const {
    register,
    handleSubmit,
    control,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<VideoFormValues>({
    resolver: zodResolver(videoFormSchema),
    defaultValues,
  });

  const orientation = watch("orientation");

  // Mock submission – logs data and simulates a short async delay
  const onSubmit = async (data: VideoFormValues) => {
    await new Promise((resolve) => setTimeout(resolve, 800)); // fake network call
    console.log("✅ Form submitted:", data);
  };

  return (
    <div className="flex flex-col gap-4 max-w-4xl mx-auto p-4">
      <div className="flex">
        <h1 className="text-xl font-medium">Generate AI Videos</h1>
      </div>

      <Alert className="bg-yellow-500/10">
        <AlertCircle />
        <p>
          This is a personal project by Yash Agrawal (<a
            href="https://www.linkedin.com/in/yash-ag-online/"
            className="underline italic"
          >
            LinkedIn
          </a>), created as part of his learning journey in AI engineering. It
          is intended solely for educational and experimental purposes and is
          not meant for commercial use.
          <br />
          <br />
          Yash Agrawal is not responsible for any incorrect, misleading, or
          inappropriate content generated by the AI system. As this project
          involves artificial intelligence, the outputs may contain errors or
          inaccuracies.
        </p>
      </Alert>

      <form onSubmit={handleSubmit(onSubmit)}>
        <FieldSet className="border p-4">
          {/* Prompt */}
          <Field>
            <FieldLabel>Prompt</FieldLabel>
            {errors.prompt && <FieldError>{errors.prompt.message}</FieldError>}
            <Textarea
              placeholder="write your video description here..."
              {...register("prompt")}
              {...register("prompt")}
            />
          </Field>

          <FieldGroup className="grid sm:grid-cols-2 md:grid-cols-3">
            {/* Quality */}
            <Controller
              name="quality"
              control={control}
              render={({ field }) => (
                <Field>
                  <FieldLabel>Select Quality</FieldLabel>
                  {errors.quality && (
                    <FieldError>{errors.quality.message}</FieldError>
                  )}
                  <ButtonGroup>
                    {(["4k", "1080", "720", "480"] as const).map((q) => (
                      <Button
                        key={q}
                        type="button"
                        variant={field.value === q ? "default" : "outline"}
                        onClick={() => field.onChange(q)}
                      >
                        {q}
                      </Button>
                    ))}
                  </ButtonGroup>
                </Field>
              )}
            />

            {/* Duration */}
            <Controller
              name="duration"
              control={control}
              render={({ field }) => (
                <Field>
                  <FieldLabel>Select Duration</FieldLabel>
                  {errors.duration && (
                    <FieldError>{errors.duration.message}</FieldError>
                  )}
                  <ButtonGroup>
                    {(["0.5-2 mins", "2-4 mins"] as const).map((d) => (
                      <Button
                        key={d}
                        type="button"
                        variant={field.value === d ? "default" : "outline"}
                        onClick={() => field.onChange(d)}
                      >
                        {d}
                      </Button>
                    ))}
                  </ButtonGroup>
                </Field>
              )}
            />

            {/* Orientation */}
            <Controller
              name="orientation"
              control={control}
              render={({ field }) => (
                <Field>
                  <FieldLabel>Select Orientation</FieldLabel>
                  {errors.orientation && (
                    <FieldError>{errors.orientation.message}</FieldError>
                  )}
                  <ButtonGroup>
                    <Button
                      type="button"
                      variant={field.value === "landscape"
                        ? "default"
                        : "outline"}
                      onClick={() => field.onChange("landscape")}
                    >
                      <Monitor className="h-4 w-4" />
                      Landscape
                    </Button>
                    <Button
                      type="button"
                      variant={field.value === "portrait"
                        ? "default"
                        : "outline"}
                      onClick={() => field.onChange("portrait")}
                    >
                      <Smartphone className="h-4 w-4" />
                      Portrait
                    </Button>
                  </ButtonGroup>
                </Field>
              )}
            />

            <Button
              type="submit"
              disabled={isSubmitting}
              className="mt-auto col-span-full"
            >
              <Sparkles />
              {isSubmitting ? "Generating…" : "Generate"}
            </Button>
          </FieldGroup>

          {/* Video preview — aspect ratio & max-width driven by orientation */}
          <div
            className={cn(
              "border bg-muted flex items-center justify-center text-muted-foreground text-sm transition-all duration-300",
              orientation === "landscape"
                ? "w-full aspect-video" // 16:9 full width
                : "mx-auto aspect-9/16 w-64", // 9:16 centered, fixed width
            )}
          >
            {orientation === "landscape" ? "16:9 Preview" : "9:16 Preview"}
          </div>
        </FieldSet>
      </form>
    </div>
  );
}

export default App;
